version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
    labels:
      - "dependencies"
      - "minor"
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/report-viewer"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"



